### ISSUE TITLE
您好，代码可能失效，期待您的更新

### ISSUE THREAD

**Issue by goyiming** [TiyaAnlite/xybAutoSign#2]
![微信截图_20220406231838](https://user-images.githubusercontent.com/81207933/162009309-5dd8d869-97b6-4bfc-ada8-6dadd90033c3.png)

**Comment by TiyaAnlite** [comment]
> ![微信截图_20220406231838](https://user-images.githubusercontent.com/81207933/162009309-5dd8d869-97b6-4bfc-ada8-6dadd90033c3.png)

今日已经注意到这个问题，正在尝试定位原因，今晚12点前应该暂时无法解决，请先尝试进行手动签退

**Comment by acbzdm** [comment]
你好，使用openid或账密都无法签到。openid报错如下
2022-04-06 23:17:33,145 - XybAccount - INFO: 正在使用OpenID登录
2022-04-06 23:18:33,201 - XybSign - ERROR: 载入账户时出现异常
2022-04-06 23:18:33,265 - XybSign - ERROR: HTTPSConnectionPool(host='xcx.xybsyw.com', port=443): Max retries exceeded with url: /login/login!wx.action (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)'))))
requests.exceptions.ProxyError: HTTPSConnectionPool(host='xcx.xybsyw.com', port=443): Max retries exceeded with url: /login/login!wx.action (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)'))))

**Comment by TiyaAnlite** [comment]
> 你好，使用openid或账密都无法签到。openid报错如下 2022-04-06 23:17:33,145 - XybAccount - INFO: 正在使用OpenID登录 2022-04-06 23:18:33,201 - XybSign - ERROR: 载入账户时出现异常 2022-04-06 23:18:33,265 - XybSign - ERROR: HTTPSConnectionPool(host='xcx.xybsyw.com', port=443): Max retries exceeded with url: /login/login!wx.action (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))) requests.exceptions.ProxyError: HTTPSConnectionPool(host='xcx.xybsyw.com', port=443): Max retries exceeded with url: /login/login!wx.action (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)'))))

这个不是程序本身的问题，是由于你的代理配置有问题(Your proxy appears to only use HTTP and not HTTPS)，请检查你的代理配置或者暂时关闭代理后重试

**Comment by acbzdm** [comment]
代理配置应该在哪里检查，我没有用vpn。使用的是ipv6的网络。

**Comment by TiyaAnlite** [comment]
> 代理配置应该在哪里检查，我没有用vpn。使用的是ipv6的网络。

你的是win还是linux

**Comment by acbzdm** [comment]
Win10，我好像知道原因了，应该是我开的抓包软件，我早上起来再试试，谢谢你

**Comment by acbzdm** [comment]
代码并非失效而是只能签到不能签退。签退会显示以下内容。
2022-04-07 08:37:03 已签到,执行重新签到
2022-04-07 08:37:03 操作异常，请联系客服

**Comment by acbzdm** [comment]
应该是把签到端口的签退功能屏蔽了。

**Comment by goyiming** [comment]
亲测早上签到执行成功，签退可能需要更改，需要测试账号 联系我私发给你

**Comment by TiyaAnlite** [comment]
统一说明下现在的情况：
- 签到功能仅【自动】签到接口可用
- 【更新】签到无法使用
- 【新增】签退也无法使用
- 签到/退所使用的接口目前应该没有变更，可能启用了签名验证

**Comment by muzisunqi123** [comment]
> 统一说明下现在的情况：
> 
> * 签到功能仅【自动】签到接口可用
> * 【更新】签到无法使用
> * 【新增】签退也无法使用
> * 签到/退所使用的接口目前应该没有变更，可能启用了签名验证

期待大佬更新

**Comment by acbzdm** [comment]
有人用虚拟定位的方式成功签到和签退，但我不知道是什么软件。

**Comment by TiyaAnlite** [comment]
> 有人用虚拟定位的方式成功签到和签退，但我不知道是什么软件。

虚拟定位实现是非常容易的，使用模拟器或者root过后的安卓手机均可做到

**Comment by muzisunqi123** [comment]
> > 有人用虚拟定位的方式成功签到和签退，但我不知道是什么软件。
> 
> 虚拟定位实现是非常容易的，使用模拟器或者root过后的安卓手机均可做到

大佬 现在有办法解决签退吗   签到签退苹果手机 可以用 爱思助手改位置

**Comment by TiyaAnlite** [comment]
> > > 有人用虚拟定位的方式成功签到和签退，但我不知道是什么软件。
> > 
> > 
> > 虚拟定位实现是非常容易的，使用模拟器或者root过后的安卓手机均可做到
> 
> 大佬 现在有办法解决签退吗 签到签退苹果手机 可以用 爱思助手改位置

目前还在实验中，还没有成功

**Comment by muzisunqi123** [comment]
> > > > 有人用虚拟定位的方式成功签到和签退，但我不知道是什么软件。
> > > 
> > > 
> > > 虚拟定位实现是非常容易的，使用模拟器或者root过后的安卓手机均可做到
> > 
> > 
> > 大佬 现在有办法解决签退吗 签到签退苹果手机 可以用 爱思助手改位置
> 
> 目前还在实验中，还没有成功

辛苦 给你加鸡腿

**Comment by acbzdm** [comment]
我用过fake location和mumu模拟器都不能正常签到，fake location用的是非root模式。

**Comment by TiyaAnlite** [comment]
项目已经更新，现在应该能正常使用了

**Comment by muzisunqi123** [comment]
> 项目已经更新，现在应该能正常使用了

你好 放进去了 很多人 一个也没有签到成功 但是日志显示成功的状态
